language: php

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_script:
  - composer self-update
  - composer install

script:
  - bin/phpunit --configuration travis.phpunit.xml.dist